# Generated by Django 6.0.3 on 2026-09-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Тел учителя'),
            preserve_default=False,
        ),
    ]
